const SERVER_BASE_API_URL = 'http://localhost:3000/api'
const LIMIT_SEARCH_ITEMS = 4

const ERRORS = {
  REQUEST_ERROR: 'ERROR_AL_SOLICITAR_EL_RECURSO'
}

export {
  SERVER_BASE_API_URL,
  LIMIT_SEARCH_ITEMS,
  ERRORS
}
